export * from './adminController.service';
import { AdminControllerService } from './adminController.service';
export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './matchController.service';
import { MatchControllerService } from './matchController.service';
export * from './memberController.service';
import { MemberControllerService } from './memberController.service';
export * from './payementController.service';
import { PayementControllerService } from './payementController.service';
export * from './siteController.service';
import { SiteControllerService } from './siteController.service';
export const APIS = [AdminControllerService, AuthControllerService, MatchControllerService, MemberControllerService, PayementControllerService, SiteControllerService];
