/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MatchDto { 
    id?: string;
    terrainId?: string;
    date?: string;
    startTime?: string;
    endTime?: string;
    organizerId?: string;
    type?: string;
}

