/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PayementDto { 
    id?: string;
    memberId?: string;
    matchId?: string;
    amount?: number;
    status?: string;
}

